apiVersion: v1
kind: ConfigMap
metadata:
  name: companies
  labels:
    app: companies
data:
  APP_ENV: development
  APP_NAME: companies
  SENTRY_DSN: ""
  POSTGRES_PORT: "5432"
  POSTGRES_HOSTNAME: postgres.db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_SSL_MODE: disable
  POSTGRES_SCHEMA: public
