apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companies
  template:
    metadata:
      labels:
        app: companies
    spec:
      containers:
        - name: companies
          image: docker.io/tjarkemeyer/companies:v0.1.0
          envFrom:
            - configMapRef:
                name: v1-companies
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
